# These settings are synced to GitHub by https://probot.github.io/apps/settings

_extends: .github # https://github.com/hoovbr/.github

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # A comma-separated list of topics to set on the repository
  topics: icicle, twitter-snowflake, distributed, systems, uuid, redis, ruby, id-generation
